server:
    port: ${SERVER_PORT:8080}

eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/

spring:
    application:
        name: ${APPLICATION_NAME:gateway-server}
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lower-case-service-id: true
                httpclient:
                    connect-timeout: 1000
                    response-timeout: 2s
         
info:
    app:
        name: "Gateway Server"
        description: "A service that handle authentication and authorization operations and validation of the users."
        version: "1.0.0"
        
logging:
    pattern:
        console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}