server:
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: ${APPLICATION_NAME:auth-service}
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:authservice}
        username: ${DATABASE_USERNAME:root}
        password: ${DATABASE_PASSWORD:root}
    jpa:
        show-sql: ${JPA_SHOW_SQL:true}
        properties:
            hibernate:
                format_sql: ${HIBERNATE_FORMAT_SQL:true}
        hibernate:
            ddl-auto: update

management:
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        shutdown:
            enabled: true
        health:
            probes:
                enabled: true
    info:
        env:
            enabled: true

eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: "http://localhost:8000/eureka/"

info:
    app:
        name: "Auth Service"
        description: "A service that handle authentication and authorization operations and validation of the users."
        version: "1.0.0"

logging:
    level:
        org:
            springframework:
                security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
    pattern:
        console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}