server:
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: ${APPLICATION_NAME:auth-service}
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:authservice}
        username: ${DATABASE_USERNAME:root}
        password: ${DATABASE_PASSWORD:root}
    jpa:
        show-sql: ${JPA_SHOW_SQL:true}
        properties:
            hibernate:
                format_sql: ${HIBERNATE_FORMAT_SQL:true}
        hibernate:
            ddl-auto: update

logging:
    level:
        org:
            springframework:
                security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
    pattern:
        console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}