server:
    port: ${SERVER_PORT:8085}

spring:
    application:
        name: ${APPLICATION_NAME:notification-service}
    mail:
        host: ${MAIL_HOST_NAME:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${GMAIL_USERNAME:prince08833@gmail.com}
        password: ${GMAIL_APP_PASSWORD:zmkv mfwf xhjz jyuo}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true