server:
    port: ${SERVER_PORT:8084}

spring:
    application:
        name: ${APPLICATION_NAME:presigned-url-generator-service}
    servlet:
      multipart:
          max-file-size: 5000MB
          max-request-size: 5000MB
          
com:
    e_leaning:
        cloudinary:
            name: ${CLOUDINARY_NAME:duhumawiq}
            api:
                key: ${CLOUDINARY_API_KEY:119948159122814}
                secret: ${CLOUDINARY_API_SECRET:dVF_AkcNk985SqZQcDBYErDHDZI}
                
management:
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        shutdown:
            enabled: true
        health:
            probes:
                enabled: true
    info:
        env:
            enabled: true
            
eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: "http://localhost:8000/eureka/"

info:
    app:
        name: "Presigned Url Generator Service"
        description: "A service that responsible uploading resources to cloud and generating url of the resource."
        version: "1.0.0"


logging:
    pattern:
        console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}