server:
    port: ${SERVER_PORT:8000}

spring:
    application:
        name: ${APPLICATION_NAME:eureka-server}

eureka:
    instance:
        hostname: ${HOST_NAME:localhost}
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
    pattern:
        console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}